### ISSUE TITLE
指令自定义配置

### ISSUE THREAD

**Issue by jzyzxx** [ileostar/v3-directives#30]
在提交PR前，请你确定你已经阅读了[贡献指南](https://github.com/ileostar/contribute)

#### 您使用的场景？ | 1. Your usage scenarios?
vue3
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
接入已有项目，有些指令已经实现了，安装这个插件后发现有些指令重名了，能不能指定指令进行注册

**Comment by ileostar** [comment]
好的，感谢你的ISSUE，我会尽快处理

**Comment by ileostar** [comment]
已发布新版本，将每个指令分别导出，你可以按照根据自定义命名
